# This is a basic workflow that is manually triggered

name: Deploy to DEV server

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set application.properties
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.DEV_APPLICATION_PROPERTIES }}" > src/main/resources/application.properties
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Build with Gradle Wrapper
        run: ./gradlew build
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          port: ${{ secrets.DEV_PORT }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_PRIVATE_KEY }}
          script: |
            ls -al
          
          